import type {
  CategorizationRule,
  FileMapping,
  ImportBatch,
  RawImportedRow,
  Setting,
  TransactionAnnotation,
  Transaction,
} from "@/types/finance";
import {
  buildFingerprint,
  buildRawHash,
  normalizeDescription,
  toMonthLabel,
  toMonthStart,
  toWeekLabel,
  toWeekStart,
} from "@/lib/finance";

const now = "2026-03-10T20:30:00+05:30";

function makeTransaction(input: {
  id: string;
  importBatchId: string;
  sourceType: "savings" | "credit_card";
  statementFileType: "pdf" | "csv";
  date: string;
  description: string;
  merchant: string;
  signedAmount: number;
  category: string;
  excludedFromSpend?: boolean;
  exclusionReason?: string;
  needsReview?: boolean;
  status?: "active" | "pending_review" | "excluded";
  accountLabel: string;
  statementPeriodStart?: string;
  statementPeriodEnd?: string;
}) {
  const direction = input.signedAmount < 0 ? "debit" : "credit";

  return {
    id: input.id,
    importBatchId: input.importBatchId,
    sourceType: input.sourceType,
    accountLabel: input.accountLabel,
    statementFileType: input.statementFileType,
    statementPeriodStart: input.statementPeriodStart,
    statementPeriodEnd: input.statementPeriodEnd,
    date: input.date,
    description: input.description,
    normalizedDescription: normalizeDescription(input.description),
    merchant: input.merchant,
    amount: Math.abs(input.signedAmount),
    signedAmount: input.signedAmount,
    direction,
    category: input.category,
    subcategory: undefined,
    excludedFromSpend: input.excludedFromSpend ?? false,
    exclusionReason: input.exclusionReason,
    weekLabel: toWeekLabel(input.date),
    monthLabel: toMonthLabel(input.date),
    rawRowHash: buildRawHash(input.importBatchId, Number(input.id.replace(/\D/g, "").slice(-2) || 0), input.description),
    transactionFingerprint: buildFingerprint(input.sourceType, input.date, input.description, input.signedAmount),
    confidenceScore: input.needsReview ? 0.62 : 0.94,
    needsReview: input.needsReview ?? false,
    createdAt: now,
    weekStart: toWeekStart(input.date),
    monthStart: toMonthStart(input.date),
    originBatchId: input.importBatchId,
    updatedAt: now,
    status: input.status ?? (input.needsReview ? "pending_review" : input.excludedFromSpend ? "excluded" : "active"),
  } satisfies Transaction;
}

export const mockImportBatches: ImportBatch[] = [
  {
    id: "batch-savings-2026-03-07",
    uploadedAt: "2026-03-07T19:42:00+05:30",
    sourceType: "savings",
    fileName: "OpTransactionHistory07-03-2026.pdf",
    fileType: "pdf",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
    totalRawRows: 26,
    rowsImported: 20,
    duplicatesSkipped: 4,
    rowsFlaggedForReview: 2,
    excludedRows: 5,
    parseErrors: 0,
    parserId: "icici-savings-transaction-history",
    status: "partial_review",
  },
  {
    id: "batch-card-2026-03-10",
    uploadedAt: "2026-03-10T21:05:00+05:30",
    sourceType: "credit_card",
    fileName: "CCStatement_Current10-03-2026.pdf",
    fileType: "pdf",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
    totalRawRows: 31,
    rowsImported: 24,
    duplicatesSkipped: 5,
    rowsFlaggedForReview: 2,
    excludedRows: 1,
    parseErrors: 0,
    parserId: "icici-credit-card-current",
    status: "partial_review",
  },
];

export const mockTransactions: Transaction[] = [
  makeTransaction({
    id: "txn-001",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-03",
    description: "UPI / Zomato / Order payment",
    merchant: "Zomato",
    signedAmount: -469.4,
    category: "Food",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-002",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-02",
    description: "UPI / Swiggy / Dinner order",
    merchant: "Swiggy",
    signedAmount: -799,
    category: "Food",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-003",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-02",
    description: "UPI / Salary Credit / ACME",
    merchant: "ACME Payroll",
    signedAmount: 120000,
    category: "Income",
    excludedFromSpend: true,
    exclusionReason: "salary_credit",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-004",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-04",
    description: "NEFT Rent Payment",
    merchant: "Rent",
    signedAmount: -22000,
    category: "Bills",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-005",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-05",
    description: "UPI / Electricity Board",
    merchant: "Electricity",
    signedAmount: -2840,
    category: "Bills",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-006",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-06",
    description: "UPI / ICICI CC Bill Payment",
    merchant: "ICICI Card Payment",
    signedAmount: -30000,
    category: "Transfer",
    excludedFromSpend: true,
    exclusionReason: "credit_card_payment",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-007",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-07",
    description: "UPI / Uber / Airport ride",
    merchant: "Uber",
    signedAmount: -912,
    category: "Travel",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-008",
    importBatchId: "batch-savings-2026-03-07",
    sourceType: "savings",
    statementFileType: "pdf",
    date: "2026-03-07",
    description: "ATM Cash Withdrawal",
    merchant: "ATM",
    signedAmount: -2000,
    category: "Cash",
    excludedFromSpend: true,
    exclusionReason: "cash_withdrawal",
    accountLabel: "ICICI Savings",
    statementPeriodStart: "2026-03-01",
    statementPeriodEnd: "2026-03-07",
  }),
  makeTransaction({
    id: "txn-009",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-03",
    description: "INDIGO AIRLINE, GURGAON IN",
    merchant: "IndiGo",
    signedAmount: -19136,
    category: "Travel",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-010",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-03",
    description: "PROBILLER.COM, 855-232-9555, CY",
    merchant: "Probiller",
    signedAmount: -5486.33,
    category: "Shopping",
    needsReview: true,
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-011",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-04",
    description: "STAR WINE, RUPNAGAR, IN",
    merchant: "Star Wine",
    signedAmount: -3000,
    category: "Lifestyle",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-012",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-04",
    description: "IGST-C(18)% on prior charge",
    merchant: "Tax on Charge",
    signedAmount: -19.65,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-013",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-04",
    description: "Markup Fee",
    merchant: "Markup Fee",
    signedAmount: -109.18,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-014",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-08",
    description: "BLINKIT, GURGAON, IN",
    merchant: "Blinkit",
    signedAmount: -131,
    category: "Groceries",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-015",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-08",
    description: "BLINKIT, GURGAON, IN",
    merchant: "Blinkit",
    signedAmount: -32,
    category: "Groceries",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-016",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-07",
    description: "BLINKIT, GURGAON, IN",
    merchant: "Blinkit",
    signedAmount: -360,
    category: "Groceries",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-017",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-09",
    description: "OPENAI *CHATGPT SUBSCR, OPENAI.COM US",
    merchant: "OpenAI",
    signedAmount: -1999,
    category: "Subscriptions",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-018",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-09",
    description: "PVTL Automation * Amazon Pay India Interest amount",
    merchant: "Amazon Pay",
    signedAmount: -8519.81,
    category: "Shopping",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-019",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-09",
    description: "PVTL Automation * Amazon Pay India Interest amount",
    merchant: "Amazon Pay",
    signedAmount: -113.53,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-020",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-10",
    description: "ICGST-C(18)% on fee",
    merchant: "Tax on Charge",
    signedAmount: -2.3,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-021",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-10",
    description: "Markup Fee",
    merchant: "Markup Fee",
    signedAmount: -12.78,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-022",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-10",
    description: "IGST-C(18)% on markup",
    merchant: "Tax on Charge",
    signedAmount: -7.16,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-023",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-10",
    description: "DCC Fee",
    merchant: "DCC Fee",
    signedAmount: -39.78,
    category: "Finance Charges",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-024",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-10",
    description: "PROBILLER.COM, 855-232-9555, CY",
    merchant: "Probiller",
    signedAmount: -642.3,
    category: "Shopping",
    needsReview: true,
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
  makeTransaction({
    id: "txn-025",
    importBatchId: "batch-card-2026-03-10",
    sourceType: "credit_card",
    statementFileType: "pdf",
    date: "2026-03-02",
    description: "Nykaa E Retail Pvt, Mumbai",
    merchant: "Nykaa",
    signedAmount: 10,
    category: "Refund",
    excludedFromSpend: true,
    exclusionReason: "refund",
    accountLabel: "ICICI Coral Visa",
    statementPeriodStart: "2026-02-25",
    statementPeriodEnd: "2026-03-10",
  }),
];

export const mockTransactionAnnotations: TransactionAnnotation[] = [
  {
    transactionFingerprint: buildFingerprint("savings", "2026-03-03", "UPI / Zomato / Order payment", -469.4),
    note: "Team lunch that should stay visible when reimbursements come in later.",
    tags: ["reimbursable", "work"],
    createdAt: now,
    updatedAt: now,
  },
  {
    transactionFingerprint: buildFingerprint("savings", "2026-03-04", "NEFT Rent Payment", -22000),
    note: "March apartment rent.",
    tags: ["fixed cost", "housing"],
    createdAt: now,
    updatedAt: now,
  },
];

export const mockRawRows: RawImportedRow[] = [
  {
    id: "raw-001",
    batchId: "batch-card-2026-03-10",
    rowIndex: 9,
    sourceType: "credit_card",
    rawText: "PROBILLER.COM, 855-232-9555, CY 5486.33 Dr.",
    rawHash: "raw-card-009",
    parserId: "icici-credit-card-current",
    confidenceScore: 0.62,
    reviewReason: "Merchant mismatch versus existing card descriptor.",
    needsReview: true,
    draftDescription: "PROBILLER.COM, 855-232-9555, CY",
    draftAmount: -5486.33,
    draftDate: "2026-03-03",
    canonicalTransactionId: "txn-010",
  },
  {
    id: "raw-002",
    batchId: "batch-card-2026-03-10",
    rowIndex: 24,
    sourceType: "credit_card",
    rawText: "PROBILLER.COM, 855-232-9555, CY 642.3 Dr.",
    rawHash: "raw-card-024",
    parserId: "icici-credit-card-current",
    confidenceScore: 0.59,
    reviewReason: "Near-duplicate amount/date pattern found.",
    needsReview: true,
    draftDescription: "PROBILLER.COM, 855-232-9555, CY",
    draftAmount: -642.3,
    draftDate: "2026-03-10",
    canonicalTransactionId: "txn-024",
  },
  {
    id: "raw-003",
    batchId: "batch-savings-2026-03-07",
    rowIndex: 5,
    sourceType: "savings",
    rawText: "UPI/paytm/Zomato/Order payment 469.40",
    rawHash: "raw-sav-005",
    parserId: "icici-savings-transaction-history",
    confidenceScore: 0.67,
    reviewReason: "Multiline remark truncated in PDF row extraction.",
    needsReview: true,
    draftDescription: "UPI / Zomato / Order payment",
    draftAmount: -469.4,
    draftDate: "2026-03-03",
    canonicalTransactionId: "txn-001",
  },
];

export const mockRules: CategorizationRule[] = [
  { id: "rule-1", keyword: "swiggy", category: "Food", priority: 100 },
  { id: "rule-2", keyword: "zomato", category: "Food", priority: 100 },
  { id: "rule-3", keyword: "uber", category: "Travel", priority: 100 },
  { id: "rule-4", keyword: "blinkit", category: "Groceries", priority: 100 },
  { id: "rule-5", keyword: "openai", category: "Subscriptions", priority: 95 },
  { id: "rule-6", keyword: "salary", category: "Income", priority: 90, excludeFromSpend: true },
];

export const mockSettings: Setting[] = [
  { key: "seeded", value: true },
  { key: "demoMode", value: true },
  { key: "billingCycleStartDay", value: 25 },
  { key: "showExcludedInCharts", value: false },
  { key: "themeMode", value: "light" },
];

export const mockFileMappings: FileMapping[] = [
  {
    id: "map-icici-savings-csv",
    sourceType: "savings",
    headerSignature: "transaction date|transaction remarks|withdrawal amount|deposit amount",
    dateColumn: "Transaction Date",
    descriptionColumn: "Transaction Remarks",
    debitColumn: "Withdrawal Amount (INR)",
    creditColumn: "Deposit Amount (INR)",
  },
];
